[2024-03-23T16:59:49.692+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: car_price_prediction.pipeline scheduled__2022-07-27T15:00:00+00:00 [queued]>
[2024-03-23T16:59:49.730+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: car_price_prediction.pipeline scheduled__2022-07-27T15:00:00+00:00 [queued]>
[2024-03-23T16:59:49.731+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-23T16:59:49.784+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): pipeline> on 2022-07-27 15:00:00+00:00
[2024-03-23T16:59:49.860+0000] {standard_task_runner.py:60} INFO - Started process 1311 to run task
[2024-03-23T16:59:49.876+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'car_price_prediction', 'pipeline', 'scheduled__2022-07-27T15:00:00+00:00', '--job-id', '92', '--raw', '--subdir', 'DAGS_FOLDER/hw_dag.py', '--cfg-path', '/tmp/tmpttnjc0at']
[2024-03-23T16:59:49.887+0000] {standard_task_runner.py:88} INFO - Job 92: Subtask pipeline
[2024-03-23T17:00:00.108+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 92 for task pipeline ((psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8); 1311)
[2024-03-23T17:00:04.769+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-23T17:00:04.851+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
