[2024-03-23T16:59:49.691+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: car_price_prediction.pipeline scheduled__2022-07-28T15:00:00+00:00 [queued]>
[2024-03-23T16:59:49.738+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: car_price_prediction.pipeline scheduled__2022-07-28T15:00:00+00:00 [queued]>
[2024-03-23T16:59:49.740+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-23T16:59:49.790+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): pipeline> on 2022-07-28 15:00:00+00:00
[2024-03-23T16:59:49.873+0000] {standard_task_runner.py:60} INFO - Started process 1312 to run task
[2024-03-23T16:59:49.886+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'car_price_prediction', 'pipeline', 'scheduled__2022-07-28T15:00:00+00:00', '--job-id', '90', '--raw', '--subdir', 'DAGS_FOLDER/hw_dag.py', '--cfg-path', '/tmp/tmp74dtevqz']
[2024-03-23T16:59:49.900+0000] {standard_task_runner.py:88} INFO - Job 90: Subtask pipeline
[2024-03-23T17:00:00.108+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 90 for task pipeline ((psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8); 1312)
[2024-03-23T17:00:04.748+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-23T17:00:04.822+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
